global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "backend-aws"
    metrics_path: /metrics
    static_configs:
      - targets: ["http://getting-started-1842817127.us-east-2.elb.amazonaws.com:80"]
